### PR TITLE
Implement linting tools

### PR DESCRIPTION
**Pull request by oh-math**
Implementing code styling and formatting feature with ESLint and Prettier

Described in Issue: #6

### CODE REVIEW

**Comment by oh-math** [comment]
Relatable pic of integration working 


image

**Review by Joabesv — CHANGES_REQUESTED** [review]
Update lint script to execute prettier and eslint
Pass flag **--fix** to Eslint so it can appoint and fix 
Rename script to **lint:fix**

**Comment by oh-math** [comment]
@Joabesv  applied changes

**Comment by Joabesv** [comment]
LGTM!

**Pull request merged**
